version: '3.7'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8181:8181"
    volumes:
      - ./backend:/var/www
    

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend
    
  db:
    #image: mysql:5.7.22
    build: 
      context: ./db
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3388:3306"

  # node-service:
  #   build:
  #     context: ./verificador-nota
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./verificador-nota:/app